//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTD_CallCategories
    {
        public int CallCategoryID { get; set; }
        public string CallCategoryDesc { get; set; }
        public bool Active { get; set; }
    }
}
