//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTD_Calls
    {
        public int CallID { get; set; }
        public string CallerPhone { get; set; }
        public int CallerAssocID { get; set; }
        public string user_name { get; set; }
        public System.DateTime DateOfCall { get; set; }
        public int CallStatusID { get; set; }
        public int CallCategoryID { get; set; }
    
        public virtual CTD_CallCategories CTD_CallCategories { get; set; }
        public virtual CTD_CallerAssocs CTD_CallerAssocs { get; set; }
        public virtual CTD_CallStatuses CTD_CallStatuses { get; set; }
        public virtual set_user set_user { get; set; }
    }
}
