//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTAMConnection.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AD_Audit
    {
        public System.Guid AuditID { get; set; }
        public string Action { get; set; }
        public System.DateTime DateModified { get; set; }
        public string Module { get; set; }
        public string Username { get; set; }
    }
}
