//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTAMConnection.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AD_CompanyProfiles
    {
        public System.Guid CompanyProfileID { get; set; }
        public string Catown { get; set; }
        public System.DateTime Datecomp { get; set; }
        public System.Guid FirmID { get; set; }
        public string Firmcert { get; set; }
        public string Firmhead { get; set; }
        public string Firmname { get; set; }
        public string Firmown { get; set; }
        public string Sizecat { get; set; }
        public string Srcemail { get; set; }
        public string Srcname { get; set; }
        public string Srctitle { get; set; }
        public int Totalfw { get; set; }
        public int Totalusfw { get; set; }
    }
}
