//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTAMConnection.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AD_Firms
    {
        public System.Guid FirmID { get; set; }
        public string FirmName { get; set; }
    }
}
