//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTAMConnection.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AD_FirmDemographics
    {
        public System.Guid FirmDemographicID { get; set; }
        public string Associates { get; set; }
        public System.Guid CompanyProfileID { get; set; }
        public string Counsel { get; set; }
        public string EquityPartners { get; set; }
        public string NonEquityPartners { get; set; }
        public string OtherLawyers { get; set; }
        public string RegionName { get; set; }
    }
}
