//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTAMConnection.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AD_LeadershipDemographics
    {
        public System.Guid LeadershipDemographicID { get; set; }
        public System.Guid CompanyProfileID { get; set; }
        public string Disabled { get; set; }
        public string LGBT { get; set; }
        public string MinorityFemale { get; set; }
        public string MinorityMale { get; set; }
        public string NumberQuestion { get; set; }
        public string WhiteFemale { get; set; }
        public string WhiteMale { get; set; }
    }
}
