//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTAMConnection.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ABADIversityEntities : DbContext
    {
        public ABADIversityEntities()
            : base("name=ABADIversityEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__EFMigrationsHistory> C__EFMigrationsHistory { get; set; }
        public virtual DbSet<AD_Audit> AD_Audit { get; set; }
        public virtual DbSet<AD_Certificates> AD_Certificates { get; set; }
        public virtual DbSet<AD_CompanyProfiles> AD_CompanyProfiles { get; set; }
        public virtual DbSet<AD_FirmDemographics> AD_FirmDemographics { get; set; }
        public virtual DbSet<AD_Firms> AD_Firms { get; set; }
        public virtual DbSet<AD_JoinedLawyers> AD_JoinedLawyers { get; set; }
        public virtual DbSet<AD_LeadershipDemographics> AD_LeadershipDemographics { get; set; }
        public virtual DbSet<AD_LeftLawyers> AD_LeftLawyers { get; set; }
        public virtual DbSet<AD_PromotionsAssociatePartners> AD_PromotionsAssociatePartners { get; set; }
        public virtual DbSet<AD_ReducedHoursLawyers> AD_ReducedHoursLawyers { get; set; }
        public virtual DbSet<AD_TopTenHighestCompensations> AD_TopTenHighestCompensations { get; set; }
        public virtual DbSet<AD_UntertakenInitiatives> AD_UntertakenInitiatives { get; set; }
    }
}
